<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($user)
    {
        $qb = $this->createQueryBuilder('i');

        $qb->where('i.userImage = :user')
            ->setParameter('user', $user)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
